// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Channel struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Message struct {
	ID        uuid.UUID
	Author    uuid.UUID
	Channel   uuid.NullUUID
	Body      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Sub struct {
	UserID        uuid.UUID
	ChannelID     uuid.UUID
	Notifications sql.NullBool
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
