-- +goose Up
CREATE TABLE channels (
    id UUID PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    creator UUID NOT NULL REFERENCES users ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, creator)
);

-- +goose Down
DROP TABLE channels;