// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"app\"><h1>Welcome to Mycelium</h1><div id=\"errors\"></div><div id=\"user\" data-signals=\"{email: &#39;&#39;, username: &#39;&#39;, password: &#39;&#39;, exists: false, valid: false, &#39;user-valid&#39;: false, &#39;pass-valid&#39;: false}\"><div><p data-show=\"$valid == false\">Enter Valid Email</p><p data-show=\"$valid == true &amp;&amp; $exists == false\">Create an account:</p><p data-show=\"$valid == true &amp;&amp; $exists == true\">Welcome Back!</p><input type=\"text\" data-bind=\"email\"></div><br><div data-on-signal-change-email=\"@get(&#39;/auth/email&#39;)\" data-indicator-fetching><div data-show=\"$valid == true &amp;&amp; $exists == false\" data-on-signal-change-password=\"@get(&#39;/auth/password&#39;)\" data-on-signal-change-username=\"@get(&#39;/auth/username&#39;)\"><label>Pick a username:</label> <input type=\"text\" data-bind=\"username\"><p data-show=\"$user-valid == false\">Username invalid or not available.</p><p data-show=\"$user-valid == true\">Username available!</p><label>Password:</label> <input type=\"password\" data-bind=\"password\"><p data-show=\"$pass-valid == false\">Invalid password. Must be 12 characters long.</p><p data-show=\"$pass-valid == true &amp;&amp; $user-valid == false\">Perfect!</p><br><button data-show=\"$user-valid == true &amp;&amp; $pass-valid == true\" data-on-click=\"@post(&#39;/auth/newuser&#39;)\">Sign Up</button></div><div data-show=\"$valid == true &amp;&amp; $exists == true\" data-on-signal-change-password=\"@get(&#39;/auth/password&#39;)\"><label>Password:</label> <input type=\"password\" data-bind=\"password\"><br><button data-show=\"$pass-valid == true\" data-on-click=\"@post(&#39;/auth/login&#39;)\">Sign In</button></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
