name: cd

on:
    push:
        branches: [main]

jobs:
  deployment:
      name: Deploy
      runs-on: ubuntu-latest

      #env:
      #  DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: "1.22"
        
        - name: Build Go binary
          run: ./scripts/buildprod.sh
        
        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'

        - name: 'Build and Push with Cloud Build'
          run: gcloud builds submit -t us-south1-docker.pkg.dev/bcalternative-mycelium/mycelium-repo/mycelium:latest .

      #  - name: 'Install goose'
      #    run: go install github.com/pressly/goose/v3/cmd/goose@latest
#
      #  - name: 'Run Migrations'
      #    run: ./scripts/migrateup.sh
#
        - name: 'Check source code'
          run: git diff
        
        - name: Deploy to Cloud Run
          run: gcloud run deploy mycelium --image us-south1-docker.pkg.dev/bcalternative-mycelium/mycelium-repo/mycelium:latest --region us-south1 --allow-unauthenticated --project bcalternative-mycelium --max-instances=4
